# Generated by Django 5.0.6 on 2024-06-28 18:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(help_text='место, в котором необходимо выполнять привычку.', max_length=200, verbose_name='Место')),
                ('time', models.TimeField(help_text='время, когда необходимо выполнять привычку.', verbose_name='Время')),
                ('action', models.CharField(help_text='действие, которое представляет собой привычка.', max_length=300, verbose_name='действие')),
                ('sign_pleasant_habit', models.BooleanField(default=True, help_text='привычка, которую можно привязать к выполнению полезной привычки.', verbose_name='Приятная привычка')),
                ('periodicity', models.CharField(choices=[('1', 'Ежедневно '), ('2', 'Один раз в два дня'), ('3', 'Один раз в три дня'), ('4', 'Один раз в четыре дня'), ('5', 'Один раз в пять дня'), ('6', 'Один раз в шесть дня'), ('7', 'Один раз в неделю')], default='1', max_length=5)),
                ('reward', models.CharField(blank=True, default=None, help_text='Награда после выполнения привычки', max_length=300, null=True, verbose_name='Награда')),
                ('time_complete', models.PositiveIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение привычки')),
                ('sign_publicity', models.BooleanField(default=False, help_text='привычки можно публиковать в общий доступ ', verbose_name='Общедоступность')),
                ('data_notification', models.DateField(auto_now=True, verbose_name='Дата уведомления')),
                ('related_habit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанные привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
