# Generated by Django 5.0.6 on 2024-06-28 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_complete',
            field=models.PositiveIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(120, message='Время выполнения должно быть не больше 120 секунд.')], verbose_name='Время на выполнение привычки'),
        ),
    ]
