# Generated by Django 5.0.6 on 2024-06-26 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_notification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 26, 16, 2, 5, 446440), verbose_name='Дата и вермя уведомления'),
        ),
    ]
