# Generated by Django 5.0.6 on 2024-06-26 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_next_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='next_notification',
        ),
        migrations.AddField(
            model_name='habit',
            name='data_notification',
            field=models.DateField(blank=True, default=datetime.date(2024, 6, 26), verbose_name='Дата уведомления'),
        ),
    ]
