# Generated by Django 5.0.6 on 2024-06-26 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_data_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='data_notification',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 6, 26, 13, 51, 21, 742461, tzinfo=datetime.timezone.utc), verbose_name='Дата уведомления'),
        ),
    ]
